# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1006, 501))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.shellmanage = QtWidgets.QWidget()
        self.shellmanage.setObjectName("shellmanage")
        self.tableWidget = QtWidgets.QTableWidget(self.shellmanage)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 771, 481))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(153)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(31)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.shellmanage, "")
        self.filemanage = QtWidgets.QWidget()
        self.filemanage.setObjectName("filemanage")
        self.treeWidget = QtWidgets.QTreeWidget(self.filemanage)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 211, 481))
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.filemanage)
        self.treeWidget_2.setGeometry(QtCore.QRect(210, 0, 561, 481))
        self.treeWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_2.setAnimated(False)
        self.treeWidget_2.setAllColumnsShowFocus(False)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget_2.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.treeWidget_2.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.treeWidget_2.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.treeWidget_2.header().setCascadingSectionResizes(True)
        self.treeWidget_2.header().setDefaultSectionSize(144)
        self.treeWidget_2.header().setMinimumSectionSize(25)
        self.tabWidget.addTab(self.filemanage, "")
        self.terminal = QtWidgets.QWidget()
        self.terminal.setObjectName("terminal")
        self.textEdit = QtWidgets.QTextEdit(self.terminal)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 561, 475))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.history = QtWidgets.QListWidget(self.terminal)
        self.history.setGeometry(QtCore.QRect(560, 0, 211, 475))
        self.history.setObjectName("history")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.history.addItem(item)
        self.tabWidget.addTab(self.terminal, "")
        self.script = QtWidgets.QWidget()
        self.script.setObjectName("script")
        self.textEdit_3 = QtWidgets.QTextEdit(self.script)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 671, 383))
        self.textEdit_3.setStyleSheet("")
        self.textEdit_3.setTabChangesFocus(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gojiaoben = QtWidgets.QPushButton(self.script)
        self.gojiaoben.setGeometry(QtCore.QRect(669, 404, 111, 71))
        self.gojiaoben.setObjectName("gojiaoben")
        self.jiaobenlabel = QtWidgets.QLabel(self.script)
        self.jiaobenlabel.setGeometry(QtCore.QRect(692, 6, 61, 16))
        self.jiaobenlabel.setStyleSheet("color: rgb(230, 230, 230);")
        self.jiaobenlabel.setObjectName("jiaobenlabel")
        self.savejiaoben = QtWidgets.QPushButton(self.script)
        self.savejiaoben.setGeometry(QtCore.QRect(669, 268, 111, 71))
        self.savejiaoben.setObjectName("savejiaoben")
        self.zairujiaoben = QtWidgets.QPushButton(self.script)
        self.zairujiaoben.setGeometry(QtCore.QRect(669, 200, 111, 71))
        self.zairujiaoben.setObjectName("zairujiaoben")
        self.clearjiaoben = QtWidgets.QPushButton(self.script)
        self.clearjiaoben.setGeometry(QtCore.QRect(669, 336, 111, 71))
        self.clearjiaoben.setObjectName("clearjiaoben")
        self.layoutWidget = QtWidgets.QWidget(self.script)
        self.layoutWidget.setGeometry(QtCore.QRect(684, 27, 77, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ASP = QtWidgets.QRadioButton(self.layoutWidget)
        self.ASP.setObjectName("ASP")
        self.verticalLayout.addWidget(self.ASP)
        self.JSP = QtWidgets.QRadioButton(self.layoutWidget)
        self.JSP.setObjectName("JSP")
        self.verticalLayout.addWidget(self.JSP)
        self.PHP = QtWidgets.QRadioButton(self.layoutWidget)
        self.PHP.setObjectName("PHP")
        self.verticalLayout.addWidget(self.PHP)
        self.Bat = QtWidgets.QRadioButton(self.layoutWidget)
        self.Bat.setObjectName("Bat")
        self.verticalLayout.addWidget(self.Bat)
        self.BASH = QtWidgets.QRadioButton(self.layoutWidget)
        self.BASH.setObjectName("BASH")
        self.verticalLayout.addWidget(self.BASH)
        self.Python = QtWidgets.QRadioButton(self.layoutWidget)
        self.Python.setObjectName("Python")
        self.verticalLayout.addWidget(self.Python)
        self.jiaobenjieguo = QtWidgets.QTextEdit(self.script)
        self.jiaobenjieguo.setGeometry(QtCore.QRect(0, 382, 671, 93))
        self.jiaobenjieguo.setObjectName("jiaobenjieguo")
        self.tabWidget.addTab(self.script, "")
        self.database = QtWidgets.QWidget()
        self.database.setObjectName("database")
        self.shujuku = QtWidgets.QTextEdit(self.database)
        self.shujuku.setGeometry(QtCore.QRect(0, 0, 770, 481))
        self.shujuku.setTabChangesFocus(False)
        self.shujuku.setObjectName("shujuku")
        self.sql_peizhi = QtWidgets.QPushButton(self.database)
        self.sql_peizhi.setGeometry(QtCore.QRect(-1, -1, 92, 34))
        self.sql_peizhi.setObjectName("sql_peizhi")
        self.sql_yuju = QtWidgets.QLineEdit(self.database)
        self.sql_yuju.setEnabled(True)
        self.sql_yuju.setGeometry(QtCore.QRect(89, 0, 593, 32))
        self.sql_yuju.setReadOnly(False)
        self.sql_yuju.setObjectName("sql_yuju")
        self.sql_zhixing = QtWidgets.QPushButton(self.database)
        self.sql_zhixing.setGeometry(QtCore.QRect(680, -1, 92, 35))
        self.sql_zhixing.setObjectName("sql_zhixing")
        self.sql_textEdit = QtWidgets.QTextEdit(self.database)
        self.sql_textEdit.setGeometry(QtCore.QRect(0, 31, 771, 443))
        self.sql_textEdit.setStyleSheet("")
        self.sql_textEdit.setReadOnly(True)
        self.sql_textEdit.setObjectName("sql_textEdit")
        self.tabWidget.addTab(self.database, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 580, 61, 21))
        self.label.setObjectName("label")
        self.connectlabel = QtWidgets.QLabel(self.centralwidget)
        self.connectlabel.setGeometry(QtCore.QRect(10, 582, 60, 16))
        self.connectlabel.setAutoFillBackground(False)
        self.connectlabel.setObjectName("connectlabel")
        self.shelllabel = QtWidgets.QLabel(self.centralwidget)
        self.shelllabel.setGeometry(QtCore.QRect(75, 580, 461, 20))
        self.shelllabel.setText("")
        self.shelllabel.setObjectName("shelllabel")
        self.timelabel = QtWidgets.QLabel(self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(610, 581, 161, 20))
        self.timelabel.setText("")
        self.timelabel.setObjectName("timelabel")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(2, 498, 771, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.user = QtWidgets.QPushButton(self.layoutWidget1)
        self.user.setStyleSheet("")
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.passwd = QtWidgets.QPushButton(self.layoutWidget1)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 0, 1, 1, 1)
        self.format = QtWidgets.QPushButton(self.layoutWidget1)
        self.format.setObjectName("format")
        self.gridLayout.addWidget(self.format, 0, 2, 1, 1)
        self.chinese = QtWidgets.QPushButton(self.layoutWidget1)
        self.chinese.setObjectName("chinese")
        self.gridLayout.addWidget(self.chinese, 0, 3, 1, 1)
        self.daitianjia = QtWidgets.QPushButton(self.layoutWidget1)
        self.daitianjia.setObjectName("daitianjia")
        self.gridLayout.addWidget(self.daitianjia, 0, 4, 1, 1)
        self.loveme = QtWidgets.QPushButton(self.layoutWidget1)
        self.loveme.setObjectName("loveme")
        self.gridLayout.addWidget(self.loveme, 0, 5, 1, 1)
        self.update = QtWidgets.QPushButton(self.layoutWidget1)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 0, 6, 1, 1)
        self.adduser = QtWidgets.QPushButton(self.layoutWidget1)
        self.adduser.setObjectName("adduser")
        self.gridLayout.addWidget(self.adduser, 1, 0, 1, 1)
        self.shutdown = QtWidgets.QPushButton(self.layoutWidget1)
        self.shutdown.setObjectName("shutdown")
        self.gridLayout.addWidget(self.shutdown, 1, 1, 1, 1)
        self.open3389 = QtWidgets.QPushButton(self.layoutWidget1)
        self.open3389.setObjectName("open3389")
        self.gridLayout.addWidget(self.open3389, 1, 2, 1, 1)
        self.homepage = QtWidgets.QPushButton(self.layoutWidget1)
        self.homepage.setObjectName("homepage")
        self.gridLayout.addWidget(self.homepage, 1, 3, 1, 1)
        self.daitianjia2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.daitianjia2.setObjectName("daitianjia2")
        self.gridLayout.addWidget(self.daitianjia2, 1, 4, 1, 1)
        self.tianjia = QtWidgets.QPushButton(self.layoutWidget1)
        self.tianjia.setObjectName("tianjia")
        self.gridLayout.addWidget(self.tianjia, 1, 5, 1, 1)
        self.exit = QtWidgets.QPushButton(self.layoutWidget1)
        self.exit.setObjectName("exit")
        self.gridLayout.addWidget(self.exit, 1, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python knife V5.0   by  qianxiao996"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "URL"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "密码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IP地址"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shellmanage), _translate("MainWindow", "shell管理"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "目 录 列 表"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "文件名"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "修改时间"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "权限"))
        self.treeWidget_2.headerItem().setText(3, _translate("MainWindow", "大小"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filemanage), _translate("MainWindow", "文件管理"))
        __sortingEnabled = self.history.isSortingEnabled()
        self.history.setSortingEnabled(False)
        item = self.history.item(0)
        item.setText(_translate("MainWindow", "历史命令"))
        self.history.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.terminal), _translate("MainWindow", "虚拟终端"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">请在此输入您的脚本或者载入脚本。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">注意：PHP脚本不需要输入&lt;?php ?&gt;  直接输入PHP代码即可。</span></p></body></html>"))
        self.gojiaoben.setText(_translate("MainWindow", "执行"))
        self.jiaobenlabel.setText(_translate("MainWindow", "脚本类型"))
        self.savejiaoben.setText(_translate("MainWindow", "保存"))
        self.zairujiaoben.setText(_translate("MainWindow", "载入"))
        self.clearjiaoben.setText(_translate("MainWindow", "清空"))
        self.ASP.setText(_translate("MainWindow", "ASP"))
        self.JSP.setText(_translate("MainWindow", "JSP"))
        self.PHP.setText(_translate("MainWindow", "PHP"))
        self.Bat.setText(_translate("MainWindow", "Bat"))
        self.BASH.setText(_translate("MainWindow", "BASH"))
        self.Python.setText(_translate("MainWindow", "Python"))
        self.jiaobenjieguo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">结果将返回在这里。</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.script), _translate("MainWindow", "自写脚本"))
        self.sql_peizhi.setText(_translate("MainWindow", "配置"))
        self.sql_zhixing.setText(_translate("MainWindow", "执行"))
        self.sql_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">此位置为显示sql语句执行结果，不可编辑。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffaa00;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">执行语句前需配置sql。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffaa00;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffaa00;\">目前仅支持mysql数据库</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database), _translate("MainWindow", "数据库管理"))
        self.label.setText(_translate("MainWindow", "当前时间："))
        self.connectlabel.setText(_translate("MainWindow", "当前连接："))
        self.user.setText(_translate("MainWindow", "查询用户"))
        self.passwd.setText(_translate("MainWindow", "修改密码"))
        self.format.setText(_translate("MainWindow", "格式化c盘"))
        self.chinese.setText(_translate("MainWindow", "中文检测"))
        self.daitianjia.setText(_translate("MainWindow", "待添加"))
        self.loveme.setText(_translate("MainWindow", "联系作者"))
        self.update.setText(_translate("MainWindow", "检查更新"))
        self.adduser.setText(_translate("MainWindow", "添加用户"))
        self.shutdown.setText(_translate("MainWindow", "强制关机"))
        self.open3389.setText(_translate("MainWindow", "开启3389"))
        self.homepage.setText(_translate("MainWindow", "待添加"))
        self.daitianjia2.setText(_translate("MainWindow", "待添加"))
        self.tianjia.setText(_translate("MainWindow", "待添加"))
        self.exit.setText(_translate("MainWindow", "退出程序"))

